### ISSUE TITLE
Additional feature request for Outlook json method

### ISSUE THREAD

**Issue by Hermann99** [rseichter/automx2#18]
Hi

Can you please provide support for the new Outlook json format.
 /autodiscover/autodiscover.json/v1.0/

Regards
H

**Comment by rseichter** [comment]
I have tried to obtain the necessary information from Microsoft for many months, to no avail. Either there is none available for public consumption, or it is hidden somewhere only paying developers can access. Microsoft did not answer my questions at all. Until the necessary information is made available to me, I cannot support the new format, as much as I would like to. Perhaps you know somebody at Microsoft and can find the specifications? I'll close this isse for now, because there simply is no basis to implement this feature at this point in time.
