### ISSUE TITLE
WARNING: This is a development server. Do not use it in a production deployment starting automx2 in Ubuntu 24.04

### ISSUE THREAD

**Issue by alietss** [rseichter/automx2#24]
Dear automx2 team,

I was giving a try to your product to test the functionality but I'm receiving this warning when I run the server:

flask[93422]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.

- OS: Ubuntu 24.04
- Used your installation guide.
- 
How can I turn off the development server in a production environment?

Thanks

**Comment by rseichter** [comment]
Flask is one of the components used by automx2, and background information about the warning you are seeing is [available here](https://flask.palletsprojects.com/en/3.0.x/deploying/). Flask is not designed to handle significant workloads. For high load use cases, other WSGI servers are available, and you can pick whichever best suits your needs.

That said, the warning is just that — a warning. automx2 is by its nature a low load application which doesn't typically have to deal with hundreds of requests per minute. Based on my experience and on feedback received from various users of automx2, Flask is capable enough for their requirements. One can always begin with Flask and switch over to a different WSGI server at a later time.

Edit: I forgot to mention that setting up automx2 behind a proxy web server like Apache or NGINX is pretty much a requirement, because the proxy handles HTTPS connections. As a side effect, the proxy also serves as a "load buffer" for incoming connections.

I hope this helps.

**Comment by alietss** [comment]
Hi,

Thanks for answering and your work in this project.

Can you point to some instructions on how to change to "production" ready server(What part of the code should we pay attention).

I would like to give a try to this, but I'm worried about public facing web servers even when NGINX is fronting the requests, I was doing some research and it seems is easy to switch to Waitress, WSGI...event.

I was reading about Flask and the risky part  is that they mention is not designed to be "secure" under this development mode.

Thanks

**Comment by rseichter** [comment]
I can offer you paid support (on an hourly basis) to integrate automx2 with other WSGI servers. However, as I already mentioned other users reported that they are doing OK with Flask. It is certainly enough for a test installation.

**Comment by rseichter** [comment]
I'll close this issue because there is no technical problem. If you are interested in commercial support, you can contact me via email to _automx2 AT seichter DOT de_.
