### ISSUE TITLE
Any plans to add Microsoft auto discover.json support for new 365 Apps?

### ISSUE THREAD

**Issue by alietss** [rseichter/automx2#25]
Hi,

Do you have any plans to add support for the new auto discover json bases for new Microsoft mail applications?

Thanks

**Comment by rseichter** [comment]
This has been discussed several times over the last years, and it has been partially documented in existing issues. The short version is that Microsoft has chosen to

1. Not respond to my inquiries.
2. Not made the necessary specifications publicly available.

Unless these points change, I can't add support for the new mechanism, even though I would like to.

**Comment by bigretromike** [comment]
https://ingogegenwarth.wordpress.com/2018/05/22/get-autodv2/
https://www.msxfaq.de/exchange/autodiscover/autodiscover_v2.htm

@rseichter probably not the most ideal url but maybe something useful in the end

**Comment by rseichter** [comment]
@bigretromike Thanks. The links point to information which looks familiar to me, although it has been years since I have seen the pages. The general theme appears to be that Microsoft does not want to disclose the details of their "new" (nine years old by now) proprietory autoconfig protocol to third parties.

Reverse engineering may be possible in a suitable environment with Microsoft products running, but that's a can of worms I gladly leave to people with masochistic tendencies. 😉

**Comment by bigretromike** [comment]
yeah. same thing go to auto-detect config for outlook. You probably familiar with it but it was a small shock for me that if you try to add account from fresh outlook by opening it and going thru wizard is a different thing that adding it thru wizard from control panel > mail (microsoft outlook). Just a M$ thing - "I'm big so I can make up my own rules, what you gonna do little men"

**Comment by rseichter** [comment]
@bigretromike So many reasons to _love_ Microsoft's shenanigans, so little time... 🙄
